// +build !ignore_autogenerated

/*
Copyright 2021 morningfish.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Beluga) DeepCopyInto(out *Beluga) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Beluga.
func (in *Beluga) DeepCopy() *Beluga {
	if in == nil {
		return nil
	}
	out := new(Beluga)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Beluga) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BelugaList) DeepCopyInto(out *BelugaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Beluga, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BelugaList.
func (in *BelugaList) DeepCopy() *BelugaList {
	if in == nil {
		return nil
	}
	out := new(BelugaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BelugaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BelugaSpec) DeepCopyInto(out *BelugaSpec) {
	*out = *in
	in.DeploymentSpec.DeepCopyInto(&out.DeploymentSpec)
	in.ServiceSpec.DeepCopyInto(&out.ServiceSpec)
	in.IngressSpec.DeepCopyInto(&out.IngressSpec)
	if in.AddBindHost != nil {
		in, out := &in.AddBindHost, &out.AddBindHost
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DelBindHost != nil {
		in, out := &in.DelBindHost, &out.DelBindHost
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BelugaSpec.
func (in *BelugaSpec) DeepCopy() *BelugaSpec {
	if in == nil {
		return nil
	}
	out := new(BelugaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BelugaStatus) DeepCopyInto(out *BelugaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BelugaStatus.
func (in *BelugaStatus) DeepCopy() *BelugaStatus {
	if in == nil {
		return nil
	}
	out := new(BelugaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CallBackHost) DeepCopyInto(out *CallBackHost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CallBackHost.
func (in *CallBackHost) DeepCopy() *CallBackHost {
	if in == nil {
		return nil
	}
	out := new(CallBackHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClashSubServer) DeepCopyInto(out *ClashSubServer) {
	*out = *in
	if in.Experimental != nil {
		in, out := &in.Experimental, &out.Experimental
		*out = make(map[string]interface{}, len(*in))
		for key, val := range *in {
		}
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = make([]ClashSubServerProxy, len(*in))
		copy(*out, *in)
	}
	if in.ProxyGroup != nil {
		in, out := &in.ProxyGroup, &out.ProxyGroup
		*out = make([]ClashSubServerProxyGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClashSubServer.
func (in *ClashSubServer) DeepCopy() *ClashSubServer {
	if in == nil {
		return nil
	}
	out := new(ClashSubServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClashSubServerProxy) DeepCopyInto(out *ClashSubServerProxy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClashSubServerProxy.
func (in *ClashSubServerProxy) DeepCopy() *ClashSubServerProxy {
	if in == nil {
		return nil
	}
	out := new(ClashSubServerProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClashSubServerProxyGroup) DeepCopyInto(out *ClashSubServerProxyGroup) {
	*out = *in
	if in.Proxies != nil {
		in, out := &in.Proxies, &out.Proxies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClashSubServerProxyGroup.
func (in *ClashSubServerProxyGroup) DeepCopy() *ClashSubServerProxyGroup {
	if in == nil {
		return nil
	}
	out := new(ClashSubServerProxyGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSServer) DeepCopyInto(out *SSServer) {
	*out = *in
	if in.ProxyServer != nil {
		in, out := &in.ProxyServer, &out.ProxyServer
		*out = make([]SSSubServerProxy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSServer.
func (in *SSServer) DeepCopy() *SSServer {
	if in == nil {
		return nil
	}
	out := new(SSServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSSubServerProxy) DeepCopyInto(out *SSSubServerProxy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSSubServerProxy.
func (in *SSSubServerProxy) DeepCopy() *SSSubServerProxy {
	if in == nil {
		return nil
	}
	out := new(SSSubServerProxy)
	in.DeepCopyInto(out)
	return out
}
