# permissions for end users to edit belugas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beluga-editor-role
rules:
- apiGroups:
  - service.beluga.io
  resources:
  - belugas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.beluga.io
  resources:
  - belugas/status
  verbs:
  - get
